# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0042_auto_20171116_2207'),
        ('visualist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('same_as', models.URLField(blank=True, null=True)),
                ('oclc_fast_id', models.IntegerField(blank=True, null=True)),
                ('in_cpl_artistfiles', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('locality', models.CharField(blank=True, default='Chicago', max_length=250, null=True)),
                ('region', models.CharField(blank=True, choices=[('IL', 'Illinois'), ('IN', 'Indiana'), ('MI', 'Michigan'), ('WI', 'Wisconsin')], default='IL', max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=250, null=True)),
                ('countries', models.CharField(blank=True, choices=[('CA', 'Canada'), ('FR', 'France'), ('MX', 'Mexico'), ('US', 'United States')], default='US', max_length=250, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visualist.Source')),
            ],
            bases=('wagtailcore.page',),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('latitude', 'longitude', 'altitude')]),
        ),
    ]
