# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20171118_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='countries',
            field=models.CharField(blank=True, choices=[('CAN', 'Canada'), ('FRA', 'France'), ('MEX', 'Mexico'), ('USA', 'United States')], default='USA', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(blank=True, choices=[('IL', 'Illinois'), ('IN', 'Indiana'), ('MI', 'Michigan'), ('WI', 'Wisconsin')], default='IL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='placecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
