# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:50
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='names.Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='events.EventTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
