# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171117_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizer_of', to='names.Name'),
        ),
    ]
