# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20171118_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
