# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:02
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20171117_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='organizer_of', to='names.Name'),
        ),
    ]
