# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.CharField(choices=[('website', 'website'), ('book', 'book'), ('journal_article', 'journal article'), ('newspaper_article', 'newspaper article')], default='website', max_length=25),
        ),
    ]
