# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualist', '0003_auto_20171118_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
