# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualist', '0004_auto_20171118_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
