# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualist', '0005_extraname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraname',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='href',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('title', 'authors', 'edition')]),
        ),
    ]
