# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualist', '0001_initial'),
        ('wagtailcore', '0042_auto_20171116_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('same_as', models.URLField(blank=True, null=True)),
                ('oclc_fast_id', models.IntegerField(blank=True, null=True)),
                ('in_cpl_artistfiles', models.BooleanField(default=False)),
                ('getty_ulan_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OrganizationIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='names.Agent')),
                ('nonprofit', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('names.agent',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('agent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='names.Agent')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('x', 'other')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
            bases=('names.agent',),
        ),
        migrations.AddField(
            model_name='agent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='visualist.Source'),
        ),
    ]
