# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20171118_0305'),
        ('visualist', '0005_extraname'),
        ('names', '0006_auto_20171118_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='extra_names',
            field=models.ManyToManyField(blank=True, to='visualist.ExtraName'),
        ),
        migrations.AddField(
            model_name='organization',
            name='locations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='places.Place'),
        ),
    ]
