# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0007_auto_20171118_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='personcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='country',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phone',
            name='extension',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('country', 'area_code', 'exchange_code', 'number', 'extension')]),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set([('service', 'account')]),
        ),
    ]
