# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0042_auto_20171116_2207'),
        ('vdirectory', '0002_auto_20171117_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
