# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:06
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vcalendar', '0001_initial'),
        ('vdirectory', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=modelcluster.fields.ParentalManyToManyField(to='vdirectory.Entity'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='vcalendar.EventTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
