# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcalendar', '0003_auto_20171117_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizers',
        ),
    ]
