# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('vcalendar', '0003_eventpagegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date',
            field=models.DateField(verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='eventpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='vcalendar.EventPage'),
        ),
        migrations.AddField(
            model_name='eventpagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcalendar_eventpagetag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='vcalendar.EventPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
