# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 04:35
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vcalendar', '0006_eventcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='vcalendar.EventCategory'),
        ),
    ]
